plugins:
  - jekyll-seo-tag

port: 4001

styles:

remote_theme: kosatyi/sjt

exclude:
  - vendor
  - src

javascript:

baseurl: /mango-php

navigation: false

projects: true

brand: mango-php
title: Mango PHP
description: MongoDB Models
logo: https://i.imgur.com/0ggpWvt.png
analytics: UA-37629144-1

author:
  name: Stepan Kosatyi
  url: http://www.kosatyi.com/

toolbar:
